'use client';

import { useCallback, useEffect, useRef, useState } from 'react';
import type { Incident, StadiumState } from '@/lib/types';

/**
 * Encapsulates the proactive AI Reasoning Engine integration.
 *
 * Watches live telemetry thresholds and automatically fires the Gemini
 * reasoning API when conditions breach:
 * - Any gate density > 80% (crowd crush risk)
 * - Any unattended bin fill level > 85% (overflow risk)
 *
 * A lock (`hasTriggeredAILock`) prevents duplicate calls: the AI is only
 * triggered once per threshold breach event, not on every tick, and the
 * lock resets once all sensors return to normal operating parameters.
 *
 * @param stadiumState - Current live telemetry to monitor.
 * @param addIncident - Callback to persist new incidents generated by the AI.
 */
export function useAiReasoning(
  stadiumState: StadiumState,
  addIncident: (incident: Omit<Incident, 'id' | 'timestamp' | 'status'>) => Promise<void>,
) {
  const [aiAnalyzing, setAiAnalyzing] = useState(false);
  const hasTriggeredAILock = useRef(false);

  /**
   * Posts the full current telemetry snapshot to the `/api/reasoning`
   * route handler, which calls Gemini (or the sandbox mock fallback) and
   * returns a structured incident recommendation.
   *
   * Uses a ref so the callback always captures fresh telemetry without
   * needing to be recreated on every state update.
   */
  const runAiReasoningEngine = useCallback(
    async (latest?: StadiumState) => {
      const telemetry = latest ?? stadiumState;
      setAiAnalyzing(true);
      try {
        const response = await fetch('/api/reasoning', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            gates: telemetry.gates,
            bins: telemetry.bins,
            concessions: telemetry.concessions,
            weather: telemetry.weather,
            nearby_medical_cases: telemetry.nearby_medical_cases,
          }),
        });

        if (!response.ok) throw new Error('API reasoning request failed');
        const analysisResult = await response.json();

        // Only persist actionable incidents — filter baseline "all clear" scans
        if (
          analysisResult.incident_type !== 'ROUTINE' ||
          analysisResult.action_plan.recommended_action.includes('Redirect') ||
          analysisResult.action_plan.recommended_action.includes('empty') ||
          analysisResult.action_plan.recommended_action.includes('Clear')
        ) {
          await addIncident({
            incident_type: analysisResult.incident_type,
            problem: analysisResult.analysis.current_state,
            reasoning: analysisResult.analysis.predictive_reasoning,
            recommended_action: analysisResult.action_plan.recommended_action,
            confidence: analysisResult.confidence || 92,
            message_for_volunteer:
              analysisResult.broadcast_payload.staff_script ||
              analysisResult.action_plan.recommended_action,
            target_zone: analysisResult.action_plan.target_zone,
            dispatched_resource_id: analysisResult.action_plan.dispatched_resource_id,
            algorithmic_routing_priority: analysisResult.action_plan.algorithmic_routing_priority,
            broadcast_payload: analysisResult.broadcast_payload,
          });
        }
      } catch (e) {
        console.error('Failed to run AI reasoning:', e);
      } finally {
        setAiAnalyzing(false);
      }
    },
    [addIncident, stadiumState],
  );

  // Proactively trigger AI when telemetry thresholds are breached
  useEffect(() => {
    const peakCrowd = Object.values(stadiumState.gates).some((g) => g.density > 80);
    const peakBin = Object.values(stadiumState.bins).some(
      (b) => b.fill_level > 85 && !b.assigned_crew,
    );

    if (peakCrowd || peakBin) {
      if (!hasTriggeredAILock.current) {
        hasTriggeredAILock.current = true;
        const timer = setTimeout(() => {
          void runAiReasoningEngine(stadiumState).catch((e) =>
            console.error('Failed to run proactive AI reasoning:', e),
          );
        }, 2000);
        return () => clearTimeout(timer);
      }
    } else {
      // Reset lock once all systems return to normal operating parameters
      hasTriggeredAILock.current = false;
    }
  }, [stadiumState, runAiReasoningEngine]);

  return { aiAnalyzing, runAiReasoningEngine };
}
